### ISSUE TITLE
Why using "with no grad" druing warping?

### ISSUE THREAD

**Issue by ZhouWeikun** [WHU-GPCV/SatMVS#7]
First, thanks for your excellent work.
But, I wonder why  "with no grad" is used in the warping process, does it means that the process of warping itself is not differentiable?

**Comment by yGaoJiany** [comment]
The warping is a _hard structure_. There is no learnable parameters. So, there is no need to calculate the gradient for the module.

**Comment by ZhouWeikun** [comment]
Ok, thanks for your answer.
